postgres:
  database: graph_service
  user: graph_service
  password: graph_service
  host: localhost
  port: 5432
  minsize: 1
  maxsize: 5

#db: postgres
#db: redis
db: mem

api:
  host: 127.0.0.1
  port: 8080